// <auto-generated />
namespace Code_first.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class okul_vt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(okul_vt));
        
        string IMigrationMetadata.Id
        {
            get { return "202206240820092_okul_vt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
