//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        internal static string About_Desc {
            get {
                return ResourceManager.GetString("About.Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        internal static string Login_Login {
            get {
                return ResourceManager.GetString("Login.Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        internal static string Login_Password {
            get {
                return ResourceManager.GetString("Login.Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Adı.
        /// </summary>
        internal static string Login_Username {
            get {
                return ResourceManager.GetString("Login.Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        internal static string Login_Welcome {
            get {
                return ResourceManager.GetString("Login.Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merhaba.
        /// </summary>
        internal static string NavBar_Hi {
            get {
                return ResourceManager.GetString("NavBar.Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitelerim.
        /// </summary>
        internal static string QuickUser_MyActivity {
            get {
                return ResourceManager.GetString("QuickUser.MyActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loglar ve Bildirimler.
        /// </summary>
        internal static string QuickUser_MyActivity_desc {
            get {
                return ResourceManager.GetString("QuickUser.MyActivity.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajlarım.
        /// </summary>
        internal static string QuickUser_MyMessage {
            get {
                return ResourceManager.GetString("QuickUser.MyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelen Kutusu ve Görevler.
        /// </summary>
        internal static string QuickUser_MyMessage_desc {
            get {
                return ResourceManager.GetString("QuickUser.MyMessage.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilim.
        /// </summary>
        internal static string QuickUser_MyProfile {
            get {
                return ResourceManager.GetString("QuickUser.MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesap Ayarları ve fazlası.
        /// </summary>
        internal static string QuickUser_MyProfile_desc {
            get {
                return ResourceManager.GetString("QuickUser.MyProfile.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görevlerim.
        /// </summary>
        internal static string QuickUser_MyTask {
            get {
                return ResourceManager.GetString("QuickUser.MyTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Görevlerim ve Projelerim.
        /// </summary>
        internal static string QuickUser_MyTask_desc {
            get {
                return ResourceManager.GetString("QuickUser.MyTask.desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        internal static string QuickUser_SignOut {
            get {
                return ResourceManager.GetString("QuickUser.SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı Profili.
        /// </summary>
        internal static string QuickUser_Title {
            get {
                return ResourceManager.GetString("QuickUser.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelle.
        /// </summary>
        internal static string QuickUser_UpdateProfile {
            get {
                return ResourceManager.GetString("QuickUser.UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIM Yönetim Sistemine Hoşgeldiniz.
        /// </summary>
        internal static string Site_Title {
            get {
                return ResourceManager.GetString("Site.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        internal static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
    }
}
